#!/bin/bash
set -euo pipefail
hugo --minify
rm -f public/local.json
git checkout gh-pages
rsync -Pa --delete-after --exclude static --exclude .git public/ .
git add .
git commit -m "Publishing $(date)"
git checkout trunk
